packages:
  - 'apps/*'
  - 'packages/*'
  - 'external-packages/*'
  - 'packages/editor-extensions/*'
  - 'extension-samples/mix'
  - 'extension-samples/preset-ui/*'
  - 'extension-samples/custom-ui-react/*'
  - 'extension-samples/custom-ui-vue/*'
  - 'extension-samples/custom-ui-solid/*'
  - 'extension-samples/custom-ui-svelte/*'
