packages:
  - 'apps/*'
  - 'packages/*'
  - 'external-packages/*'
  - 'packages/editor-extensions/*'
  - 'extension-samples/preset-ui/*'
  - 'extension-samples/custom-ui-react/*'
  - 'extension-samples/vue/*'
  - 'extension-samples/extension-template-solid/*'
  - 'extension-samples/svelte/*'
